version: 2

services:
  - type: static-site
    name: frontend
    sourceDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist

  - type: pserv
    name: database
    env: postgres

  - type: web
    name: backend
    sourceDir: backend
    env: docker
    dockerfilePath: Dockerfile
    dependsOn:
      - database
    envVars:
      - fromService:
          type: pserv
          name: database
          property: connectionString
        to: DATABASE_URL
      - key: PORT
        value: 8080